env: 
  node: true
  browser: true
rules:
  eqeqeq: 0
  curly: error
  quotes:
    - error
    - "double"
language: node_js
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
install:
  - npm install yo -g
  - npm install yo html-5-bp
